### ISSUE TITLE
Only one month is shown when numberOfMonths/numberOfColumns is set to 2

### ISSUE THREAD

**Issue by mrassili** [wakirin/Litepicker#108]
**Describe the bug**
The calendar displays 1 month even though we have 2 months in the config
We had it working as expected a week ago and now we can only see one month being displayed

We didn't do any change since more than a week.
We use litepicker from the CDN:
`<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js"></script>`

**To Reproduce**
[Codesandbox](https://codesandbox.io/s/litepicker-repro-3n2wv)

**Expected behavior**
It should display two months

**jsfiddle.net / codepen.io / etc**
[Codesandbox](https://codesandbox.io/s/litepicker-repro-3n2wv)

**Additional context**
-

**Comment by wakirin** [comment]
I see 2 months.
If you are talking about displaying on mobile, then add to config:
`mobileFriendly: false`

see #102

**Comment by mrassili** [comment]
> I see 2 months.

That's weird:
<img width="1916" alt="Screen Shot 2020-06-17 at 2 17 11 PM" src="https://user-images.githubusercontent.com/25288435/84902850-43189b80-b0a5-11ea-8c69-d4f289f0ecf2.png">

>If you are talking about displaying on mobile, then add to config:
mobileFriendly: false

no I'm talking about desktop which was working up until today :(

**Comment by scott-fisher-iii** [comment]
@mrassili It probably isn't a good idea to be using the non-versioned CDN link in production.
<pre><script src="https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js"></script></pre>

There are a few ways to do this.
Since this package is not available via NuGet (only npm) we have some projects that cannot use the package as a reference per-say. So in that case, I have downloaded a copy of the version and then just reference that JS file locally.

Another way to do this is to use the versioned CDN link:
<pre><script src="https://cdn.jsdelivr.net/npm/litepicker@1.4.7/dist/js/main.js"></script></pre>
<pre><script src="https://cdn.jsdelivr.net/npm/litepicker@1.4.4/dist/js/main.js"></script></pre>

**Comment by mrassili** [comment]
thank you @scott-fisher-iii version 1.4.7 is working alright
but still there's a bug introduced in 1.5.0 I guess

**Comment by scott-fisher-iii** [comment]
@wakirin Perhaps the versioned link should also be added to the help doc?

**Comment by wakirin** [comment]
I will add a link to https://www.jsdelivr.com/features#npm in readme.

@scott-fisher-iii 
the problem is reproduced by your side https://codesandbox.io/s/litepicker-repro-3n2wv ?

**Comment by wakirin** [comment]
@mrassili 
how many months is displayed here https://codepen.io/wakirin/pen/rNxWwep ?

**Comment by scott-fisher-iii** [comment]
I see the problem (only 1 month showing instead of 2) with @mrassili 's codeandsandbox.io link, but not the codepen.io link that @wakirin just shared.

**Comment by mrassili** [comment]
> @mrassili
> how many months is displayed here https://codepen.io/wakirin/pen/rNxWwep ?

two

**Comment by mrassili** [comment]
The one @wakirin shared on codepen uses 1.5.1 version which works, I think the bug is on 1.5.0

**Comment by scott-fisher-iii** [comment]
Yeah, I noticed the CDN link is still 1.5.0
https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js

You can specify 1.5.1 though with:
https://cdn.jsdelivr.net/npm/litepicker@1.5.1/dist/js/main.js

**Comment by mrassili** [comment]
okay that explains it. thanks!
