### ISSUE TITLE
Disable dropdown when field is readonly

### ISSUE THREAD

**Issue by jaquino94** [wakirin/Litepicker#112]
**Is your feature request related to a problem? Please describe.**
We are using Litepicker with input fields for our forms; however, there are forms where the input field is readonly. The problem is even though the field is readonly, the user can still click on the field and the dropdown selection still appears. 

**Describe the solution you'd like**
A method to disable the dropdown would be great as we can just invoke it

**Comment by scott-fisher-iii** [comment]
If you do implement this, please make sure it is optional. 

We have several uses where the textbox is readonly because we only want entry done via the picker (so we can ensure it is properly formatted for various locales).

@jaquino94 perhaps you could add logic to the **onShow** event?
Perhaps something like this: https://jsfiddle.net/szpa1kcb/5/
This utilizes the readOnly property defined here that supports all modern browsers:
https://www.w3schools.com/jsref/prop_text_readonly.asp

**Comment by wakirin** [comment]
@scott-fisher-iii provided a good solution for this case.
Closed.
