### ISSUE TITLE
Feature: touch for scrolling months

### ISSUE THREAD

**Issue by Saltibarsciai** [wakirin/Litepicker#149]
**Is your feature request related to a problem? Please describe.**
Better user experience would be if one could swipe months to the side or down like in carousel

**Describe the solution you'd like**
Add option `swipe: true/false` which would enable wrapper carousel, maybe [tiny-slider](https://github.com/ganlanyuan/tiny-slider) would do the work and `swipe-direction=true/false`

**Describe alternatives you've considered**
I haven't found datepicker with such feature, therefore only alternative left is to change package

**Additional context**
I have litepicker here, but can't swipe to change month, it would be awesome if I could
![Screenshot_19](https://user-images.githubusercontent.com/57238127/101014441-8f319c80-356e-11eb-8d82-ad71bfdab928.png)

**Comment by wakirin** [comment]
https://wakirin.github.io/Litepicker/docs/plugins#mobile-friendly-plugin

**Comment by markVerb** [comment]
Is there any way to maintain this swipe functionality but to customize / limit the animation?
I would really just prefer to be able to swipe (drag) horizontally between months (like a carousel) instead of having the animation kick in part way through dragging and then overtake my drag and snap to the next month.

I hope this makes sense.

This is a second call for this request here https://github.com/wakirin/Litepicker/issues/244
