### ISSUE TITLE
Duplicated month

### ISSUE THREAD

**Issue by AlexanderHorn672** [wakirin/Litepicker#18]
Congrats to this great calendar, have replaced all other widgets with it by now!

Today, Dec 30, 2019, for some reason March 2020 is showing twice, instead of February 2020. Have tried to find a reason, but no luck so far. Just guessing, maybe due to Feb having 29 days this year?

Page is here: https://rincondelmar.club/disponibilidad12meses.html

![image](https://user-images.githubusercontent.com/20998028/71612035-0989bd80-2b63-11ea-9f29-d94d4c3f2b41.png)

**Comment by myraumhafen** [comment]
Similar problem here. You can check it also on the demo site. The effect appears when you set e.g. a minDate (e.g. 2019-12-31). Then open the calendar. You see the months December and January. Then change the month forward in the calendar. Then you see March and April instead of February and March. If you change the month backward the February appears und all is correct. Perhaps a leap-year problem. 
I make a short video to demonstrate the problem: 
https://www.dropbox.com/s/9p0jb62nda0ssd7/Bildschirmaufnahme.mov?dl=0

Thank you very much for your work! :-)

**Comment by wakirin** [comment]
Thanks, I fixed it just now, check please v1.0.20

**Comment by wakirin** [comment]
@myraumhafen fixed in v1.0.21

**Comment by myraumhafen** [comment]
Thank you very much for the fast fix. It works 👍 
I wish you a happy new year and thank you very much for your work!
