### ISSUE TITLE
render:day is not working 

### ISSUE THREAD

**Issue by evromalarkey** [wakirin/Litepicker#182]
**Describe the bug**
render:day is not working correctly in inline mode, it renders only after clicking on body and then it loops

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/L6o4b71v/1/

**Comment by wakirin** [comment]
I have tested on codepen.io and locally there is no problem.
Looks like a bug on jsfiddle.
If you want catch first render in inline mode, you can add in setup:
```
setup: (picker) => {
  picker.on("render:day", (day) => {
    console.log(day)
  });
  picker.render(); 
}
```

**Comment by wakirin** [comment]
As I can see the jsfiddle freezing when you use console.log with a lot of HTML elements.

https://jsfiddle.net/1wuqo4cj/

Perhaps this is due to their beta console, it shows HTMLElement in great detail and very slowly.
Unfortunately disabling the beta console in the editor settings does not help, it seems to disable only the visual part.

**Comment by evromalarkey** [comment]
Yeah it seems the loop and the freezing is bug of jsfiddle, I didn't notice this locally. 

Is there any particular reason to add `picker.render()` for it to work though? I would expect this to work right away with render:day, it was working this way with `renderDay` event previously.

**Comment by wakirin** [comment]
@evromalarkey 
try with 2.0.4, should work without extra `picker.render()`.

**Comment by evromalarkey** [comment]
works great, thanks!
