### ISSUE TITLE
Inline calendar doesn't 'move to' the predefined selected range

### ISSUE THREAD

**Issue by mijrs** [wakirin/Litepicker#195]
**Describe the bug/problem**
If you click on a predefined range, the inline calendar doesn't 'move to' the new selected range.

**To Reproduce**
https://jsfiddle.net/Mijrs/2htfd1oy/29/

Click on 'first week January 2021'. You see the calendar stayes at February. Would like the calendar jumped to the selected/clicked period in January.

**Expected behaviour**
After clicking on a predefined range, the inline calendar has to move (show) to the new selected date range.

**Comment by wakirin** [comment]
I will fix it in the next release.
Currently you can fix it with `selected` event: https://jsfiddle.net/2sLfxjqg/

**Comment by wakirin** [comment]
fixed in 2.0.9

**Comment by mijrs** [comment]
I've updated the jsfiddle with 2.0.9, but i don't see a change. 

https://jsfiddle.net/Mijrs/2htfd1oy/31/

**Comment by wakirin** [comment]
https://jsfiddle.net/gyqute5b/

Use plugin `ranges` from 2.0.9 version.

**Comment by mijrs** [comment]
Thnx!

**Comment by harrington101** [comment]
I am using the plugin for ranges. The first calendar moves but the second does not. The calendars are not connected so the user can move one calendar without moving the other in order to select a larger range of dates. Expected behavior: The first calendar should show the start of the range and the second calendar should show the end of the range.

**Comment by wakirin** [comment]
@harrington101 
nice catch. I forgot about `splitView` option.
I will fix it in the next release.
