### ISSUE TITLE
Adding custom html to the picker

### ISSUE THREAD

**Issue by glennvdbroeck** [wakirin/Litepicker#35]
I wanted to add "quick date range options" to the calendar. A small button to trigger specific ranges like: today, last 7 days, this month, etc...

<img width="574" alt="Schermafbeelding 2020-02-18 om 00 53 32" src="https://user-images.githubusercontent.com/47667332/74692890-99ee9100-51e9-11ea-869e-ea333c1a614e.png">

I was able to add them with the onShow callback function.

```
onShow: function () {
var quickPicks = document.createElement('div');
quickPicks.setAttribute('class', 'container-fluid px-1');
var quickOption = document.createElement('a');
quickOption.setAttribute('class', 'btn btn-sm btn-primary m-1');
quickOption.setAttribute('href', '#');
quickOption.innerHTML = 'Last 30 days';
quickOption.addEventListener("click", function () {
    this.setDateRange(moment().subtract(29, 'days').toDate(), moment().toDate());
    this.hide();
 }, false);
quickPicks.appendChild(quickOption);
document.getElementsByClassName('container__months')[0].appendChild(quickPicks);
}
```
This works when the picker gets opened. The buttons even work before any other interaction with the calendar.
But as soon as I interact with the calendar (select one date in the calendar, or change months) the _quickPicks_ disappear immediately.
I assume the div's are getting destroyed each time an interaction takes place. (That makes sense when changing months, but that doesn't seem intuitive when only selecting a date range).

How could it be possible to add custom html to the calendar that remains after interactions?

**Comment by glennvdbroeck** [comment]
It seems in calendar.ts
```
this.picker.innerHTML = '';
this.picker.appendChild(months);
```
totally resets the whole html of the component on each render() call.

**Comment by glennvdbroeck** [comment]
I have it "working" by hijacking all onSelect, changeMonth events and adding the custum html there.
Maybe a callback after the render() event would make this easier?

**Comment by wakirin** [comment]
Sure, PR is welcome.

**Comment by glennvdbroeck** [comment]
PR created.

**Comment by wakirin** [comment]
Thanks for PR.
v1.0.31 is published.

**Comment by hmaesta** [comment]
Hey guys.

I wasted way more time than I wanted to find a lightweight datepicker for Vue – and failed completely. Found out Litepicker and was super excited, but the lack of a Vue version and missing shortcut buttons was very disappointing. 

But, _kind of by accident,_ I found this issue and it was super encouraging. @glennvdbroeck did a great job hacking the project and it was the base for me to start  – and now I am happy to say that I could achieve partially what I wanted:

![Screen Shot 2020-07-23 at 09 41 01](https://user-images.githubusercontent.com/741969/88287724-16215f00-ccc9-11ea-9707-d5f8383d9d80.png)

[Vue + Litepicker + Shortcut buttons on Codesandbox](https://codesandbox.io/s/vue-litepicker-shortcuts-tsb5u?file=/src/App.vue) 🥳

I am not a great Javascript developer, but I thought that maybe I could help this project with a PR of these shortcut buttons.  But the first problem is: how to use the same date library as user? Is that a way to find (and them import) the right package? 

For example, @glennvdbroeck is using Moment, but I prefer date-fns. Since we need only basic and few functions, I thought we could ship the package "plug-and-play" for Moment, date-fns and Day.js – without installing any of them by default, just verifying what is already there and using appropriately.
