### ISSUE TITLE
One more event, which will fire on startDate select on singleMode: false

### ISSUE THREAD

**Issue by iPasha** [wakirin/Litepicker#63]
onSelect event now fires on `singleMode: false` when endDate selected. It would be helpful to have event which fires on startDate select.

**Comment by wakirin** [comment]
Could you explain in which case you need a start date without an end date ?

**Comment by iPasha** [comment]
I'm developing a popup to show full upcoming year. It has header, where selected date is shown and a body with calendars, which has overflow: scroll property and shows only two months at a time. So, when user selects startDate and scrolls down, I want to show something like "20.04.2020 — ..." in the header, so user is sure to select right date. Example of such behavior can be found at onetwotrip.com search form.

**Comment by wakirin** [comment]
I think you can do something like this:
https://jsfiddle.net/udsbwtf2/1/

If you use `inlineMode`, you need to replace the `onHide` event with `onSelect`.
In this example the `onHide` event is required because  the user can click outside the calendar after selecting a start date and  this will hide the calendar.
