### ISSUE TITLE
scrollToDate is broken

### ISSUE THREAD

**Issue by Yannik** [wakirin/Litepicker#92]
**Describe the bug**
The datepicker does not open the correct month if the startDate is in the future.

**To Reproduce**
```
<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.js"></script>
<input type="text" id="form-start-date"/>

<script>
    var picker = new Litepicker({
        element: document.getElementById('form-start-date'),
        minDate: '2021/01/01',
        scrollToDate: true
    });
</script>
```

**Expected behavior**
It should open the month of january 2021 

**Actual behavior**
It opens the current month (may 2020), where no date is selectable.

**jsfiddle.net / codepen.io / etc**
https://jsfiddle.net/6dghLvaf/

**Comment by scott-fisher-iii** [comment]
Two things I'm noticing:
First, you are technically using a custom date format.
The default date format is:
<pre>YYYY-MM-DD</pre>
You are using slashes instead of hyphens.
I tried swapping that out and that didn't solve it. Just an observation.

The main issue I think you are seeing is that the definition on the help/doc page states that *scrollToDate* is a boolean indicating if you should "Scroll to start date on open."
However, you don't have a start date, you have a minimum date. Those are not the same.
You can try swapping *minDate* for *startDate* and it works as you describe in the expected behavior.

If you don't want to make an actual selection, but just to use a starting month displayed in the calendar you can call the *gotoDate* method after creating a picker object. This will set the view of the calendar to the specified date/month without making the selection.

**Comment by wakirin** [comment]
@scott-fisher-iii is right.
`scrollToDate` is not broken.
